import React, { useState } from "react";

function Pill({ verdict }) {
  const color =
    verdict === "CONFIRMED"
      ? "pill-green"
      : verdict === "PARTIAL"
      ? "pill-yellow"
      : "pill-red";

  return <span className={`pill ${color}`}>{verdict}</span>;
}

function ScanResult({ result }) {
  const {
    tokenName,
    symbol,
    contractAddress,
    narrativeClaim,
    verdict,
    verdictReasoning,
    notesForUser,
    projectSummary,
    entities,
    cached,
    marketData,
    socials,
    securityData,
    confidence,
    sentimentScore,
    fundamentals,
    birdeye,
  } = result;

  const [copySuccess, setCopySuccess] = useState(false);

  const formatFullReport = () => {
    let report = `DYOR SCAN REPORT\n`;
    report += `${"=".repeat(50)}\n\n`;
    report += `TOKEN: ${tokenName || "Unknown Token"} (${symbol || "N/A"})\n`;
    report += `CONTRACT: ${contractAddress}\n`;
    report += `VERDICT: ${verdict || "N/A"} (${confidence || "N/A"} confidence)\n`;
    report += `SENTIMENT SCORE: ${sentimentScore || "N/A"}/100\n`;
    report += `\n${"=".repeat(50)}\n\n`;

    report += `SUMMARY\n`;
    report += `${"-".repeat(50)}\n`;
    report += `${notesForUser || "No summary available."}\n\n`;

    if (marketData) {
      report += `MARKET DATA\n`;
      report += `${"-".repeat(50)}\n`;
      if (marketData.price) report += `Price: $${parseFloat(marketData.price).toFixed(8)}\n`;
      if (marketData.liquidity) report += `Liquidity: $${(marketData.liquidity / 1000000).toFixed(2)}M\n`;
      if (marketData.volume24h) report += `24h Volume: $${(marketData.volume24h / 1000000).toFixed(2)}M\n`;
      if (marketData.priceChange24h) report += `24h Change: ${marketData.priceChange24h >= 0 ? '+' : ''}${marketData.priceChange24h.toFixed(2)}%\n`;
      report += `\n`;
    }

    if (fundamentals) {
      report += `FUNDAMENTALS\n`;
      report += `${"-".repeat(50)}\n`;
      if (fundamentals.supply) report += `Supply: ${fundamentals.supply}\n`;
      if (fundamentals.holderCount) report += `Holders: ${fundamentals.holderCount}\n`;
      if (fundamentals.mintAuthority) report += `Mint Authority: ${fundamentals.mintAuthority}\n`;
      report += `\n`;
    }

    report += `NARRATIVE CLAIM\n`;
    report += `${"-".repeat(50)}\n`;
    report += `${narrativeClaim || "No narrative extracted."}\n\n`;

    report += `VERDICT REASONING\n`;
    report += `${"-".repeat(50)}\n`;
    report += `${verdictReasoning || "No reasoning provided."}\n\n`;

    if (result.redFlags && result.redFlags.length > 0) {
      report += `RED FLAGS\n`;
      report += `${"-".repeat(50)}\n`;
      result.redFlags.forEach((flag, idx) => {
        report += `${idx + 1}. ${flag}\n`;
      });
      report += `\n`;
    }

    if (entities) {
      report += `ENTITIES\n`;
      report += `${"-".repeat(50)}\n`;
      if (entities.organizations?.length > 0) {
        report += `Organizations: ${entities.organizations.join(", ")}\n`;
      }
      if (entities.products?.length > 0) {
        report += `Products: ${entities.products.join(", ")}\n`;
      }
      if (entities.topics?.length > 0) {
        report += `Topics: ${entities.topics.join(", ")}\n`;
      }
      report += `\n`;
    }

    if (securityData?.risks?.length > 0) {
      report += `SECURITY RISKS\n`;
      report += `${"-".repeat(50)}\n`;
      securityData.risks.forEach((risk, idx) => {
        report += `${idx + 1}. [${risk.level}] ${risk.description}\n`;
      });
      report += `\n`;
    }

    report += `Generated by DYOR Scanner\n`;
    report += `${new Date().toISOString()}\n`;

    return report;
  };

  const handleCopyReport = async () => {
    try {
      const report = formatFullReport();
      await navigator.clipboard.writeText(report);
      setCopySuccess(true);
      setTimeout(() => setCopySuccess(false), 2000);
    } catch (err) {
      console.error("Failed to copy:", err);
    }
  };

  const summaryText = notesForUser || `Analysis of ${tokenName || "Unknown Token"} (${symbol || "N/A"}) - Verdict: ${verdict || "N/A"} (${confidence || "N/A"} confidence). ${verdictReasoning || ""}`;

  return (
    <section className="scan-result">
      <div className="result-header">
        <div>
          <h2>
            {tokenName || "Unknown Token"} {symbol && <span>({symbol})</span>}
          </h2>
          <p className="ca">CA: {contractAddress}</p>
        </div>
        <div className="verdict-block">
          {verdict && <Pill verdict={verdict} />}
          {cached && <span className="cached-tag">cached</span>}
        </div>
      </div>

      <div className="result-actions">
        <button onClick={handleCopyReport} className="btn-copy-report">
          {copySuccess ? "✓ Copied!" : "📋 Copy Full Report"}
        </button>
      </div>

      <div className="result-summary">
        <h3>Summary</h3>
        <p>{summaryText.substring(0, 500)}{summaryText.length > 500 ? "..." : ""}</p>
      </div>

      {result.hasMarketData === false && (
        <div className="result-section">
          <div className="warning-box">
            <h3>⚠️ No Market Data Available</h3>
            <p>This token has no trading pairs on decentralized exchanges. It may be very new, unlaunched, or have no liquidity. Exercise extreme caution.</p>
          </div>
        </div>
      )}

      {marketData && (
        <div className="result-section">
          <h3>Market Data</h3>
          <div className="market-stats">
            {marketData.price && (
              <div className="stat">
                <span className="stat-label">Price</span>
                <span className="stat-value">${parseFloat(marketData.price).toFixed(8)}</span>
              </div>
            )}
            {marketData.liquidity && (
              <div className="stat">
                <span className="stat-label">Liquidity</span>
                <span className="stat-value">${(marketData.liquidity / 1000000).toFixed(2)}M</span>
              </div>
            )}
            {marketData.volume24h && (
              <div className="stat">
                <span className="stat-label">24h Volume</span>
                <span className="stat-value">${(marketData.volume24h / 1000000).toFixed(2)}M</span>
              </div>
            )}
            {marketData.priceChange24h && (
              <div className="stat">
                <span className="stat-label">24h Change</span>
                <span className={`stat-value ${marketData.priceChange24h >= 0 ? 'positive' : 'negative'}`}>
                  {marketData.priceChange24h >= 0 ? '+' : ''}{marketData.priceChange24h.toFixed(2)}%
                </span>
              </div>
            )}
          </div>
          {marketData.dexUrl && (
            <a href={marketData.dexUrl} target="_blank" rel="noopener noreferrer" className="dex-link">
              View on DexScreener →
            </a>
          )}
        </div>
      )}

      {socials && (socials.website || socials.x || socials.telegram) && (
        <div className="result-section">
          <h3>Social Links</h3>
          <div className="socials-list">
            {socials.website && (
              <a href={socials.website} target="_blank" rel="noopener noreferrer" className="social-item">
                🌐 Website
              </a>
            )}
            {socials.x && (
              <a href={socials.x} target="_blank" rel="noopener noreferrer" className="social-item">
                𝕏 Twitter
              </a>
            )}
            {socials.telegram && (
              <a href={socials.telegram} target="_blank" rel="noopener noreferrer" className="social-item">
                📱 Telegram
              </a>
            )}
          </div>
        </div>
      )}

      {securityData && securityData.risks && securityData.risks.length > 0 && (
        <div className="result-section">
          <h3>Security Risks</h3>
          <div className="security-risks">
            {securityData.risks.map((risk, idx) => (
              <div key={idx} className="risk-item">
                <span className="risk-level">{risk.level}</span>
                <span className="risk-description">{risk.description}</span>
              </div>
            ))}
          </div>
        </div>
      )}

      <div className="result-section">
        <h3>What this token is saying</h3>
        <p>{narrativeClaim || "No narrative extracted yet."}</p>
      </div>

      <div className="result-section">
        <h3>Our provisional read</h3>
        <p className="notes">{notesForUser}</p>
        <p className="reasoning">Model reasoning: {verdictReasoning}</p>
      </div>

      <div className="result-section">
        <h3>Entities</h3>
        {entities ? (
          <div className="entities">
            <div>
              <h4>Organizations</h4>
              <ul>
                {entities.organizations?.map((o) => (
                  <li key={o}>{o}</li>
                ))}
              </ul>
            </div>
            <div>
              <h4>Products</h4>
              <ul>
                {entities.products?.map((p) => (
                  <li key={p}>{p}</li>
                ))}
              </ul>
            </div>
            <div>
              <h4>Topics</h4>
              <ul>
                {entities.topics?.map((t) => (
                  <li key={t}>{t}</li>
                ))}
              </ul>
            </div>
          </div>
        ) : (
          <p>No entities parsed.</p>
        )}
      </div>

      <div className="result-section">
        <h3>Raw summary</h3>
        <pre className="summary-pre">{projectSummary}</pre>
      </div>

      {result.redFlags && result.redFlags.length > 0 && (
        <div className="result-section">
          <h3>⚠️ Red Flags</h3>
          <ul className="red-flags-list">
            {result.redFlags.map((flag, idx) => (
              <li key={idx}>{flag}</li>
            ))}
          </ul>
        </div>
      )}

      {result.confidence && (
        <div className="result-section">
          <h3>Analysis Confidence</h3>
          <div className="confidence-indicator">
            <span className={`confidence-level confidence-${result.confidence}`}>
              {result.confidence.toUpperCase()}
            </span>
            <p className="confidence-note">
              {result.confidence === 'high' && 'We have strong evidence to support this verdict.'}
              {result.confidence === 'medium' && 'This verdict is based on available information, but more research is recommended.'}
              {result.confidence === 'low' && 'Limited information available. Exercise caution and do thorough research.'}
            </p>
          </div>
        </div>
      )}
    </section>
  );
}

export default ScanResult;

